workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    exfunc-OAS:
        inputs:
            - location: ./spec/exfunc_v1_openapi_spec.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/nunchi/nunchi/exfunc-oas
targets:
    exfunc:
        target: python
        source: exfunc-OAS
